
services:
  db:
    image: postgres:15
    container_name: finance-db
    environment:
      POSTGRES_DB: financeapi
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"

  app:
    build: .
    environment:
      DB_URL: jdbc:postgresql://db:5432/financeapi
      DB_USER: admin
      DB_PASS: admin
      DB_DRIVER: org.postgresql.Driver
    depends_on:
      - db
