spring:
  datasource:
    url: jdbc:h2:mem:financeapi
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # cria/atualiza tabelas automaticamente no H2
    show-sql: true
    properties:
      jakarta.persistence.schema-generation.database.action: none
  flyway:
    enabled: false      # desativa migrations do Flyway no teste

# Configurações H2 Console (opcional)
spring.h2.console:
  enabled: true
  path: /h2-console
